---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library("tidyverse")
library("janitor")
library("here")
library("skimr")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
HR <- read_csv(here("data/heartrate.csv")) %>% clean_names
```

```{r}
glimpse(HR)
```
```{r}
HR %>% 
  select(a, patient) %>% 
  ggplot(aes(x=patient, fill=patient, y=a))+
  geom_col()+
  labs(title="Comparison of drug A",
       x="Patient",
       y="Heartrate")
       
```

2. Make a plot that compares heartrate (as a range) for each drug.

```{r}
HR %>% 
  pivot_longer(-patient,
               names_to="drug",
               values_to="heartrate") %>% 
  ggplot(aes(x=drug, fill=drug, y=heartrate))+
  geom_boxplot(alpha=0.7)+
  labs(title="Comparison of heartrate drugs",
       x="Drugs",
       y="Heartrate")
```

